import './App.css';
import React from "react";
import {connect} from "react-redux";
import Amplify, {Signer} from '@aws-amplify/core';
import {Auth, Hub} from "aws-amplify";
import {BrowserRouter} from 'react-router-dom';
import ApplicationBase from 'terra-application/lib/application-base';
import ApplicationLoadingOverlay from 'terra-application/lib/application-loading-overlay';
import PageContainer from "./Views/PageContainer/PageContainer";
import {
    setAllergyData,
    setConditionData,
    setDiagnosticData,
    setMedicationData,
    setObservationData,
    setPatientData,
    setProcedureData,
    setRawData
} from "./Actions/patientContextActions";
import {setErrorFlag, setLoadingFlag, unsetLoadingFlag} from "./Actions/appStateActions";
import {updateLoginState} from "./Actions/loginActions";
import {Grid} from "semantic-ui-react";
import Login from "./Components/Authentication/Login";
import 'semantic-ui-css/semantic.min.css';
import awsconfig from './aws-exports'

const axios = require('axios');
require('dotenv').config()

Amplify.configure(awsconfig);
Auth.configure(awsconfig);

class App extends React.Component {
    _isMounted;

  constructor(props) {
    super(props);
    this.state = {
        patient: null,
        currentLoginState: "signedOut",
        tgt: null
    }
  }

  async componentDidMount() {
      this._isMounted = true;
      this.setAuthListener();
      const {client, setPatientData, setAllergyData, setMedicationData, setObservationData, setConditionData,
          setDiagnosticData, setProcedureData, setRawData, setLoadingFlag, unsetLoadingFlag, setErrorFlag} = this.props;
      try {
          setLoadingFlag();
          let endpointPath = process.env.REACT_APP_HealthLake_Endpoint;
          let credentials = await Auth.currentCredentials();
          //===============================---Fetching Patient Data from HealthLake---==================================
          // For demo purposes, a randomly selected patient from autogenerated HealthLake Synthea data
          let patient_id = "7be33b47-d5ae-4c7a-83ee-2bbe8f439a92";
          // Fetch Patient details
          let patient;
          try {
              patient = await this.healthLakeDataFetcher(endpointPath + "Patient/" + patient_id, credentials);
              console.log("Patient Response: ", patient);
              setPatientData(patient.data);
          } catch (e) {
              console.log("Fetching Patient Resource failed: ", e);
          }
          // Fetch Observation data
          let observation;
          try {
              observation = await this.healthLakeDataFetcher(endpointPath + "Observation?subject=Patient/" + patient_id, credentials);
              console.log("Observation Response: ", observation);
          } catch (e) {
              console.log("Fetching Observation Resource failed: ", e);
          }
          // Fetch Allergy data
          let allergy;
          try {
              let allergyURL = Signer.signUrl(endpointPath + "/AllergyIntolerance", {
                  access_key: credentials.accessKeyId,
                  secret_key: credentials.secretAccessKey,
                  session_token: credentials.sessionToken,
              })
              allergy = await axios.get(allergyURL);
              console.log("AllergyIntolerance Response: ", allergy);
          } catch (e) {
              console.log("Fetching AllergyIntolerance Resource failed: ", e);
          }
          // Fetch Medication data
          let medication;
          try {
              let medicationURL = Signer.signUrl(endpointPath + "/MedicationRequest", {
                  access_key: credentials.accessKeyId,
                  secret_key: credentials.secretAccessKey,
                  session_token: credentials.sessionToken,
              })
              medication = await axios.get(medicationURL);
              console.log("Medication Response: ", medication);
          } catch (e) {
              console.log("Fetching MedicationRequest Resource failed: ", e);
          }
          // Fetch DiagnosticReports data
          let diagnosticReports;
          try {
              let diagnosticURL = Signer.signUrl(endpointPath + "/DiagnosticReport", {
                  access_key: credentials.accessKeyId,
                  secret_key: credentials.secretAccessKey,
                  session_token: credentials.sessionToken,
              })
              diagnosticReports = await axios.get(diagnosticURL);
              console.log("DiagnosticReport Response: ", diagnosticReports);
          } catch (e) {
              console.log("Fetching DiagnosticReport Resource failed: ", e);
          }
          // Process Data
          let observationArray= [];
          if (observation) {
              if (observation.data) {
                  observation = observation.data;
                  if (observation.entry.length > 0) {
                      observation.entry.forEach(observed => {
                          if (!observed.resource.issue) {
                              observationArray.push(observed);
                          }
                                 })
                  }
                  console.log("observationArray", observationArray);
                  setObservationData(observationArray);
              }
          }

          let allergyArray = [];
          if (allergy) {
              if (allergy.length > 0) {
              for (let array of allergy) {
                  if (array.entry) {
                      if (array.entry.length > 0) {
                          array.entry.forEach(item => {
                              allergyArray.push(item);
                          })
                      }
                  }
              }
                  setAllergyData({allergies: allergyArray});
              }
          }

          let medicationArray = [];
          if (medication) {
              if (medication.length > 0) {
              for (let array of medication) {
                  if (array.entry) {
                      if (array.entry.length > 0) {
                          array.entry.forEach(item => {
                              medicationArray.push(item);
                          })
                      }
                  }
              }
                  setMedicationData({medications: medicationArray});
              }
          }
          let diagnosticReportArray = [];
          if (diagnosticReports) {
              if (diagnosticReports.length > 0) {
                  for (let array of diagnosticReports) {
                      if (array.entry) {
                          if (array.entry.length > 0) {
                              array.entry.forEach(item => {
                                  diagnosticReportArray.push(item);
                              })
                          }
                      }
                  }
                  setDiagnosticData({diagnostics: diagnosticReportArray, client: client});
              }
          }
          let procedures;
          try {
              let procedureURL = Signer.signUrl(endpointPath + "/Procedure", {
                  access_key: credentials.accessKeyId,
                  secret_key: credentials.secretAccessKey,
                  session_token: credentials.sessionToken,
              })
              procedures = await axios.get(procedureURL);
              console.log("Procedure Response: ", procedures);
          } catch (e) {
              console.log("Fetching Procedure Resource failed: ", e);
          }
          let proceduresArray = [];
          if (procedures) {
              if (procedures.length > 0) {
                  for (let array of procedures) {
                      if (array.entry) {
                          if (array.entry.length > 0) {
                              array.entry.forEach(item => {
                                  proceduresArray.push(item);
                              })
                          }
                      }
                  }
                  setProcedureData(proceduresArray);
              }

          }
          let conditions;
          try {
              let conditionURL = Signer.signUrl(endpointPath + "/Condition", {
                  access_key: credentials.accessKeyId,
                  secret_key: credentials.secretAccessKey,
                  session_token: credentials.sessionToken,
              })
              conditions = await axios.get(conditionURL);
              console.log("Condition Response: ", conditions);
          } catch (e) {
              console.log("Fetching Condition Resource failed: ", e);
          }
          let conditionArray = [];
          if (conditions) {
              if (conditions.length > 0) {
                  for (let array of conditions) {
                      if (array.entry.length > 0) {
                          array.entry.forEach(item => {
                              conditionArray.push(item);
                          })
                      }
                      }
                  setConditionData(conditionArray);
                  }
              }
          //===================================---End of HealthLake Data Fetch ---===================================
          setRawData({observations: observationArray, allergies: allergyArray,
                      medications: medicationArray, conditions: conditionArray, procedures: proceduresArray,
                      diagnosticReports: diagnosticReportArray});


          if (this._isMounted) {
              this.setState({
                  patient: patient.data,
              })
          }
          unsetLoadingFlag();
      } catch (err) {
          setErrorFlag();
          unsetLoadingFlag();
          console.error("Error requesting FHIR resources: ", err);
      }
  }

  healthLakeDataFetcher = async (endpointPath, credentials) => {
      let dataURL = Signer.signUrl(endpointPath, {
          access_key: credentials.accessKeyId,
          secret_key: credentials.secretAccessKey,
          session_token: credentials.sessionToken,
      })
      return await axios.get(dataURL);
  }

   setAuthListener = async () => {
      const {updateLoginState} = this.props;
        Hub.listen('auth', (data)=> {
            switch(data.payload.event) {
                case "signOut":
                    updateLoginState("signIn");
                    break;
                default:
                    break;
            }
        })
    }

  componentWillUnmount() {
      this._isMounted = false;
  }

  componentDidUpdate(prevProps, prevState, snapshot) {
      if (this.props.loginState !== prevProps.loginState) {
          this.setState({
              currentLoginState: this.props.loginState,
          })
      }
  }

    render() {
      const {client, isLoadingData, errorOccurred} = this.props;
      const {patient} = this.state;
      let name = "";
      if (patient) {
         console.log("patient debug", patient);
          name = patient.name[0].given[0] + " " + patient.name[0].family;

          if (patient.name[0].prefix) {
              name =  patient.name[0].prefix[0] + " " + name;
          }
      }


  return (
      <ApplicationBase locale={"en"} >
          {
              this.props.loginState !== "signedIn" && (
                  <div  className="App" style={{height: "100vh", width: "100vw"}}>
                      <Login animateTitle={false} type={"image"} title={"Antimicrobial Insights"} darkMode={false} />
                  </div>
              )
          }
          {
              this.props.loginState === "signedIn" && (
                  <div className="App" style={{height: "100vh", width: "100vw", backgroundColor: "#f2f8fc"}}>
                      {
                          (isLoadingData)? <ApplicationLoadingOverlay isOpen={isLoadingData} /> :
                              (errorOccurred)? <Grid style={{height: "100vh", width: "100vw", backgroundColor: "#f2f8fc"}}>
                                      <Grid.Row style={{height: "100vh", width: "100vw", backgroundColor: "#f2f8fc"}}>
                                          <Grid.Column verticalAlign={"middle"} textAlign={"center"}>
                                              <h1>Sorry, an error occurred while retrieving patient data from the server.</h1>
                                              <h1>Please refresh or re-launch the application.</h1>
                                          </Grid.Column>
                                      </Grid.Row>
                                  </Grid> :
                                  <BrowserRouter>
                                      <PageContainer client={client} name={name}/>
                                  </BrowserRouter>
                      }
                  </div>
              )
          }
      </ApplicationBase>
  );
}

}

const mapStateToProps = (state) => {
    return {
        isLoadingData: state.appState.loadingPatientData,
        errorOccurred: state.appState.error,
        loginState: state.loginState.currentState,
    };
};


const mapDispatchToProps = {
    setPatientData,
    setAllergyData,
    setLoadingFlag,
    unsetLoadingFlag,
    setMedicationData,
    setObservationData,
    setConditionData,
    setDiagnosticData,
    setProcedureData,
    setRawData,
    setErrorFlag,
    updateLoginState,
}

export default connect(mapStateToProps, mapDispatchToProps)(App);
