import './App.css';
import React from "react";
import {connect} from "react-redux";
import Amplify, {Signer} from '@aws-amplify/core';
import {Auth, Hub} from "aws-amplify";
import {BrowserRouter} from 'react-router-dom';
import ApplicationBase from 'terra-application/lib/application-base';
import ApplicationLoadingOverlay from 'terra-application/lib/application-loading-overlay';
import PageContainer from "./Views/PageContainer/PageContainer";
import {
    setAllergyData,
    setConditionData,
    setDiagnosticData,
    setMedicationData,
    setObservationData,
    setPatientData,
    setProcedureData,
    setRawData
} from "./Actions/patientContextActions";
import {setErrorFlag, setLoadingFlag, unsetLoadingFlag} from "./Actions/appStateActions";
import {updateLoginState} from "./Actions/loginActions";
import {Grid} from "semantic-ui-react";
import Login from "./Components/Authentication/Login";
import 'semantic-ui-css/semantic.min.css';
import awsconfig from './aws-exports'

const axios = require('axios');
require('dotenv').config()

Amplify.configure(awsconfig);
Auth.configure(awsconfig);

class App extends React.Component {
    _isMounted;

  constructor(props) {
    super(props);
    this.state = {
        patient: null,
        currentLoginState: "signedOut",
    }
  }

  async componentDidMount() {
      this._isMounted = true;
      this.setAuthListener();
      const {setPatientData, setRawData, setLoadingFlag, unsetLoadingFlag, setErrorFlag} = this.props;
      try {
          setLoadingFlag();
          let endpointPath = process.env.REACT_APP_HealthLake_Endpoint;
          let credentials = await Auth.currentCredentials();
          //========================================---Fetching Patient Data from HealthLake---================================================
          // For demo purposes, a randomly selected patient from autogenerated HealthLake Synthea data
          let patient_id = "7be33b47-d5ae-4c7a-83ee-2bbe8f439a92";
          // Fetch Patient details
          let patient;
          try {
              patient = await this.healthLakeDataFetcher(endpointPath + "Patient/" + patient_id, credentials);
              console.log("Patient Response: ", patient);
              setPatientData(patient.data);
          } catch (e) {
              console.log("Fetching Patient Resource failed: ", e);
          }
          // Fetch Observation data
          let observation;
          try {
              observation = await this.healthLakeDataFetcher(endpointPath + "Observation?subject=Patient/" + patient_id, credentials);
              console.log("Observation Response: ", observation);
          } catch (e) {
              console.log("Fetching Observation Resource failed: ", e);
          }
          // Fetch Allergy data
          let allergy;
          try {
              // TODO
              allergy = await this.healthLakeDataFetcher(endpointPath + "AllergyIntolerance?patient=Patient/" + patient_id, credentials);
              console.log("AllergyIntolerance Response: ", allergy);
          } catch (e) {
              console.log("Fetching AllergyIntolerance Resource failed: ", e);
          }
          // Fetch Medication data
          let medication;
          try {
              medication = await this.healthLakeDataFetcher(endpointPath + "MedicationRequest?subject=Patient/" + patient_id, credentials);
              console.log("Medication Response: ", medication);
          } catch (e) {
              console.log("Fetching MedicationRequest Resource failed: ", e);
          }
          // Fetch DiagnosticReports data
          let diagnosticReports;
          try {
              diagnosticReports = await this.healthLakeDataFetcher(endpointPath + "DiagnosticReport?subject=Patient/" + patient_id, credentials);
              console.log("DiagnosticReport Response: ", diagnosticReports);
          } catch (e) {
              console.log("Fetching DiagnosticReport Resource failed: ", e);
          }
          // Fetch Procedure data
          let procedures;
          try {
              procedures = await this.healthLakeDataFetcher(endpointPath + "Procedure?subject=Patient/" + patient_id, credentials);
              console.log("Procedure Response: ", procedures);
          } catch (e) {
              console.log("Fetching Procedure Resource failed: ", e);
          }
          // Fetch Condition data
          let conditions;
          try {
              conditions = await this.healthLakeDataFetcher(endpointPath + "Condition?subject=Patient/" + patient_id, credentials);
              console.log("Condition Response: ", conditions);
          } catch (e) {
              console.log("Fetching Condition Resource failed: ", e);
          }
          //===========================================================---Process Data---===============================================
          let observationArray = [];
          if (observation) {
              observationArray = this.dataProcessor(observation.data, "Observation");
          }

          let allergyArray = [];
          if (allergy) {
              allergyArray = this.dataProcessor(allergy.data, "AllergyIntolerance");
          }

          let medicationArray = [];
          if (medication) {
              medicationArray = this.dataProcessor(medication.data, "MedicationRequest");
          }
          let diagnosticReportArray = [];
          if (diagnosticReports) {
              diagnosticReportArray = this.dataProcessor(diagnosticReports.data, "DiagnosticReport");
          }

          let proceduresArray = [];
          if (procedures) {
              proceduresArray = this.dataProcessor(procedures.data, "Procedure");
          }

          let conditionArray = [];
          if (conditions) {
             conditionArray = this.dataProcessor(conditions.data, "Condition");
              }
          //=========================================================================================================
          setRawData({observations: observationArray, allergies: allergyArray,
                      medications: medicationArray, conditions: conditionArray, procedures: proceduresArray,
                      diagnosticReports: diagnosticReportArray});


          if (this._isMounted) {
              this.setState({
                  patient: patient.data,
              })
          }
          unsetLoadingFlag();
      } catch (err) {
          setErrorFlag();
          unsetLoadingFlag();
          console.error("Error requesting FHIR resources: ", err);
      }
  }

  dataProcessor = (data, type) => {
      const {client, setAllergyData, setMedicationData, setObservationData, setConditionData,
          setDiagnosticData, setProcedureData} = this.props;

      let dataArray = [];
      if (data) {
          if (data.entry.length > 0) {
              data.entry.forEach(observed => {
                  if (!observed.resource.issue) {
                      dataArray.push(observed);
                  }
              })
          }
      }

      switch (type) {
          case "Observation":
              setObservationData(dataArray);
              break;
          case "AllergyIntolerance":
              setAllergyData({allergies: dataArray});
              break;
          case "MedicationRequest":
              setMedicationData({medications: dataArray});
              break;
          case "Condition":
              setConditionData(dataArray);
              break;
          case "DiagnosticReport":
              setDiagnosticData({diagnostics: dataArray, client: client});
              break;
          case "Procedure":
              setProcedureData(dataArray);
              break;
          default:
              break;
      }

      return dataArray;
  }

  healthLakeDataFetcher = async (endpointPath, credentials) => {
      let dataURL = Signer.signUrl(endpointPath, {
          access_key: credentials.accessKeyId,
          secret_key: credentials.secretAccessKey,
          session_token: credentials.sessionToken,
      })
      return await axios.get(dataURL);
  }

   setAuthListener = async () => {
      const {updateLoginState} = this.props;
        Hub.listen('auth', (data)=> {
            switch(data.payload.event) {
                case "signOut":
                    updateLoginState("signIn");
                    break;
                default:
                    break;
            }
        })
    }

  componentWillUnmount() {
      this._isMounted = false;
  }

  componentDidUpdate(prevProps, prevState, snapshot) {
      if (this.props.loginState !== prevProps.loginState) {
          this.setState({
              currentLoginState: this.props.loginState,
          })
      }
  }

    render() {
      const {client, isLoadingData, errorOccurred} = this.props;
      const {patient} = this.state;
      let name = "";
      if (patient) {
          name = patient.name[0].given[0] + " " + patient.name[0].family;

          if (patient.name[0].prefix) {
              name =  patient.name[0].prefix[0] + " " + name;
          }
      }


  return (
      <ApplicationBase locale={"en"} >
          {
              this.props.loginState !== "signedIn" && (
                  <div  className="App" style={{height: "100vh", width: "100vw"}}>
                      <Login animateTitle={false} type={"image"} title={"Antimicrobial Insights"} darkMode={false} />
                  </div>
              )
          }
          {
              this.props.loginState === "signedIn" && (
                  <div className="App" style={{height: "100vh", width: "100vw", backgroundColor: "#f2f8fc"}}>
                      {
                          (isLoadingData)? <ApplicationLoadingOverlay isOpen={isLoadingData} /> :
                              (errorOccurred)? <Grid style={{height: "100vh", width: "100vw", backgroundColor: "#f2f8fc"}}>
                                      <Grid.Row style={{height: "100vh", width: "100vw", backgroundColor: "#f2f8fc"}}>
                                          <Grid.Column verticalAlign={"middle"} textAlign={"center"}>
                                              <h1>Sorry, an error occurred while retrieving patient data from the server.</h1>
                                              <h1>Please refresh or re-launch the application.</h1>
                                          </Grid.Column>
                                      </Grid.Row>
                                  </Grid> :
                                  <BrowserRouter>
                                      <PageContainer client={client} name={name}/>
                                  </BrowserRouter>
                      }
                  </div>
              )
          }
      </ApplicationBase>
  );
}

}

const mapStateToProps = (state) => {
    return {
        isLoadingData: state.appState.loadingPatientData,
        errorOccurred: state.appState.error,
        loginState: state.loginState.currentState,
    };
};


const mapDispatchToProps = {
    setPatientData,
    setAllergyData,
    setLoadingFlag,
    unsetLoadingFlag,
    setMedicationData,
    setObservationData,
    setConditionData,
    setDiagnosticData,
    setProcedureData,
    setRawData,
    setErrorFlag,
    updateLoginState,
}

export default connect(mapStateToProps, mapDispatchToProps)(App);
